;;; Automatically generated by ‘recentf’ on Fri Apr  7 18:57:26 2023.

(setq recentf-list
      '(
        "c:/Users/mateo/Desktop/emacs/todo.org"
        "c:/Users/mateo/AppData/Roaming/.emacs.d/config.org"
        "c:/Users/mateo/Desktop/Travail/ZZ1 S1/bdd/BDFacturation_queries2.sql"
        "c:/Users/mateo/AppData/Roaming/.emacs.d/init.el"
        "c:/Users/mateo/AppData/Roaming/.emacs.d/config.el"
        "c:/Users/mateo/Desktop/test.txt"
        "c:/Users/mateo/Desktop/testemacs.txt"
        "c:/Users/mateo/Desktop/Trackmania.url"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
